#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
readonly branch_name=`git branch`
echo $branch_name
if [ "$branch_name" = "main" ]; then
    debug "You can't commit to main branch, please checkout to another branch, skipping hook"
    exit 0
fi